default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>

development:
  <<: *default
  database: sample_rails_api_development

test:
  <<: *default
  database: sample_rails_api_test<%= ENV['TEST_ENV_NUMBER'] %>

# For production is recommended to set DATABASE_URL env variable.
# It will take precedence over the config defined here.
# https://edgeguides.rubyonrails.org/configuring.html#connection-preference
production:
  adapter: postgresql
  encoding: unicode
  database: sample_rails_api_prod
  username: postgres
  password: ruby3.3.5&rails7
  host: rails-api-db.cziioq000tsw.us-east-1.rds.amazonaws.com
  port: 5432
  pool: 5
