name: Deploy Rails App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.5'

    - name: Install PostgreSQL Client
      run: sudo apt-get install -y postgresql-client

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run yarn commands
      run: yarn install
    - name: Precompile assets
      run: bundle exec rails assets:precompile

    - name: Run Tests
      run: |
        bundle exec rake db:create RAILS_ENV=test
        bundle exec rake db:migrate RAILS_ENV=test
        HEADLESS=true bundle exec rspec

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/myapp/current
          git pull origin main
          bundle install
          yarn install
          RAILS_ENV=production bundle exec rake assets:precompile
          RAILS_ENV=production bundle exec rake db:migrate
          sudo systemctl restart nginx
